name: Chirpflow
permissions:
  contents: write
  
on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
 
      
    - name: Publish win64
      run: dotnet publish --framework net8.0 --runtime win-x64 --no-self-contained
    - name: Creating win64 zip
      run: zip -r winrelease.zip . -i src/Chirp.Web/bin/Release/net8.0/win-x64/publish/*
      
    - name: Publish osx64
      run: dotnet publish --framework net8.0 --runtime osx-x64 --no-self-contained
    - name: Creating osx-64 zip
      run: zip -r osxrelease.zip . -i src/Chirp.Web/bin/Release/net8.0/osx-x64/publish/
      
    - name: Publish osxarm64
      run: dotnet publish --framework net8.0 --runtime osx-arm64 --no-self-contained
    - name: Creating arm-x64 Zip
      run: zip -r armrelease.zip . -i src/Chirp.Web/bin/Release/net8.0/osx-arm64/publish/* 
      
    - name: Publish linux
      run: dotnet publish --framework net8.0 --runtime linux-x64 --no-self-contained
    - name: Creating linux-x64 Zip
      run: zip -r linuxrelease.zip . -i src/Chirp.Web/bin/Release/net8.0/linux-x64/publish/*

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          winrelease.zip
          osxrelease.zip
          armrelease.zip
          linuxrelease.zip
